--Display job title, department name, employee last name, starting date for all jobs from 2000 to 2005.


SELECT JOB_TITLE, DEPARTMENT_NAME, LAST_NAME, START_DATE
FROM EMPLOYEES E

JOIN DEPARTMENTS D
ON D.DEPARTMENT_ID = E.DEPARTMENT_ID

JOIN JOBS J
ON J.JOB_ID = E.JOB_ID

JOIN JOB_HISTORY H
ON H.EMPLOYEE_ID = E.EMPLOYEE_ID

WHERE TO_CHAR(H.START_DATE, 'YYYY') BETWEEN 2000 AND 2005;