SELECT EMPLOYEE_ID, LAST_NAME, EMPLOYEES.DEPARTMENT_ID, DEPARTMENTS.DEPARTMENT_ID, LOCATION_ID
FROM EMPLOYEES
JOIN DEPARTMENTS
ON (EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID);



SELECT EMPLOYEE_ID, FIRST_NAME, CITY, DEPARTMENT_NAME
FROM EMPLOYEES
JOIN DEPARTMENTS
ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID
JOIN LOCATIONS
ON DEPARTMENTS.LOCATION_ID = LOCATIONS.LOCATION_ID;



SELECT *
FROM LOCATIONS;

SELECT *
FROM EMPLOYEES;

SELECT *
FROM DEPARTMENTS;

SELECT *
FROM JOB_HISTORY;

SELECT *
FROM JOBS;


SELECT FIRST_NAME, LAST_NAME, SALARY, CITY
FROM EMPLOYEES
JOIN DEPARTMENTS
ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID
JOIN LOCATIONS
ON DEPARTMENTS.LOCATION_ID = LOCATIONS.LOCATION_ID
WHERE CITY = 'Oxford';



--Display job title, department name, employee last name, starting date for all jobs from 2000 to 2005.


SELECT JOB_TITLE, DEPARTMENT_NAME, LAST_NAME, START_DATE
FROM EMPLOYEES E

JOIN DEPARTMENTS D
ON D.DEPARTMENT_ID = E.DEPARTMENT_ID

JOIN JOBS J
ON J.JOB_ID = E.JOB_ID

JOIN JOB_HISTORY H
ON H.EMPLOYEE_ID = E.EMPLOYEE_ID

WHERE TO_CHAR(H.START_DATE, 'YYYY') BETWEEN 2000 AND 2005;


-- FULL / LEFT / RIGHT JOIN
SELECT E.LAST_NAME, E.DEPARTMENT_ID, D.DEPARTMENT_NAME
FROM employees E
--LEFT OUTER JOIN departments D
--RIGHT OUTER JOIN departments D
FULL OUTER JOIN departments D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;

SELECT FIRST_NAME, DEPARTMENT_NAME
FROM employees
CROSS JOIN departments;