-- Chapter 6

-- Task 4
SELECT MAX(SALARY) "Maximun", MIN(SALARY) "Minimum", SUM(SALARY) "Sum", ROUND(AVG(SALARY), 2) "Average"
FROM employees;

-- Task 5
SELECT COUNT(JOB_ID) JOB_ID, MAX(SALARY) Maximum, MIN(SALARY) Minumum, SUM(SALARY) Sum
FROM employees
GROUP BY job_id;

-- Task 6
SELECT JOB_ID, COUNT(JOB_ID)
FROM employees
GROUP BY JOB_ID;

-- Task 7
SELECT COUNT(DISTINCT(MANAGER_ID)) "Number of Managers"
FROM employees;

-- Task 9
SELECT MANAGER_ID, MIN(SALARY)
FROM EMPLOYEES
WHERE MANAGER_ID IS NOT NULL
GROUP BY MANAGER_ID
HAVING MIN(SALARY) > 6000
ORDER BY 2 DESC;

-- Task 10  (Check Book Solution)
SELECT COUNT(EMPLOYEE_ID) "TOTAL",
    SUM(CASE WHEN TO_CHAR(HIRE_DATE, 'YYYY')=2005 THEN 1 ELSE 0 END) "2005",
    SUM(CASE WHEN TO_CHAR(HIRE_DATE, 'YYYY')=2006 THEN 1 ELSE 0 END) "2006",
    SUM(CASE WHEN TO_CHAR(HIRE_DATE, 'YYYY')=2007 THEN 1 ELSE 0 END) "2007",
    SUM(CASE WHEN TO_CHAR(HIRE_DATE, 'YYYY')=2008 THEN 1 ELSE 0 END) "2008"
FROM employees;

-- Task 11  (Check Book Solution)
SELECT JOB_ID "JOB",
    SUM(CASE WHEN DEPARTMENT_ID = 20 THEN SALARY ELSE NULL END) "DEPT 20",
    SUM(CASE WHEN DEPARTMENT_ID = 50 THEN SALARY ELSE NULL END) "DEPT 50",
    SUM(CASE WHEN DEPARTMENT_ID = 80 THEN SALARY ELSE NULL END) "DEPT 80",
    SUM(CASE WHEN DEPARTMENT_ID = 90 THEN SALARY ELSE NULL END) "DEPT 90",
    SUM (SALARY) "TOTAL"
FROM EMPLOYEES
GROUP BY JOB_ID;

