-- DML (Data Manipulation Language)

DESCRIBE DEPARTMENTS;

INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID)
VALUES (71,'PR',100,1700);

--ROLLBACK;

--COMMENT;

SELECT * 
FROM DEPARTMENTS 
ORDER BY DEPARTMENT_ID;