SELECT LAST_NAME, SALARY, NVL(COMMISSION_PCT, 0), 
(SALARY*12)+ (SALARY*12*NVL(COMMISSION_PCT, 0)) AN_SAL
FROM EMPLOYEES;

SELECT LAST_NAME, SALARY, COMMISSION_PCT,
NVL2(COMMISSION_PCT, 'SALARY+COMMISSION','SALARY') "TOTAL INCOME",
(SALARY*12)+ (SALARY*12*NVL(COMMISSION_PCT, 0)) "ANNUAL SALARY"
FROM EMPLOYEES;

SELECT 
FIRST_NAME, LENGTH(FIRST_NAME) "1st NAME", 
LAST_NAME, LENGTH(LAST_NAME) "2nd NAME",
NULLIF(LENGTH(FIRST_NAME), LENGTH(LAST_NAME)) "RESULT"
-- IN RESULT = 1st and 2nd name length are same then RESULT is null.
FROM EMPLOYEES;

SELECT LAST_NAME, SALARY,
DECODE (TRUNC (SALARY/3000), 0, 0.00, 1, 0.09, 2, 0.20, 3, 0.30, 0.40) TAX_RATE
FROM EMPLOYEES
WHERE department_id = 80;