-- 3-1. Restricting  and Sorting Data --

-- 3.
SELECT LAST_NAME, SALARY
FROM employees
WHERE salary NOT BETWEEN 5000 AND 12000;

-- 5.
SELECT LAST_NAME, DEPARTMENT_ID
FROM employees
WHERE DEPARTMENT_ID IN (20, 50)
ORDER BY LAST_NAME DESC;

-- 6.
SELECT LAST_NAME "Employee", SALARY "Monthly Salary"
FROM employees
WHERE SALARY BETWEEN 5000 AND 12000 AND DEPARTMENT_ID IN (20, 50);

-- 9.
SELECT LAST_NAME, SALARY, COMMISSION_PCT
FROM employees
WHERE COMMISSION_PCT IS NOT NULL
ORDER BY 2 DESC,3 DESC;

-- 15.
SELECT LAST_NAME, SALARY, COMMISSION_PCT 
FROM employees
WHERE COMMISSION_PCT = .20;
--WHERE COMMISSION_PCT IN (0.20);

-- 2.
SELECT LAST_NAME, DEPARTMENT_ID
FROM employees
WHERE employee_id =176;
