-- 1
SELECT MIN_SALARY
FROM JOBS
WHERE MIN_SALARY > 10000;

-- 2
SELECT FIRST_NAME, HIRE_DATE
FROM EMPLOYEES
WHERE JOB_ID IN('IT_PROG', 'SA_MAN');

-- 3
SELECT *
FROM EMPLOYEES
WHERE EMPLOYEE_ID IN(150, 160);

SELECT *
FROM EMPLOYEES
WHERE EMPLOYEE_ID =150
OR EMPLOYEE_ID = 160;

-- 4
SELECT JOB_TITLE, (MAX_SALARY - MIN_SALARY) DIFFERENCE
FROM JOBS
WHERE MAX_SALARY BETWEEN 10000 AND 20000;

